ccflags-y += -Idrivers/media/platform/msm/camera_v2_leeco
ccflags-y += -Idrivers/media/platform/msm/camera_v2_leeco/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_leeco/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
