ccflags-y += -Idrivers/media/platform/msm/camera_v2_leeco
ccflags-y += -Idrivers/media/platform/msm/camera_v2_leeco/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_leeco/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_leeco/smmu
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
